### ISSUE TITLE
New feature: NSFW Disable

### ISSUE THREAD

**Issue by XxBeastKingxX** [Deivu/Kashima#1]
**What is the feature that you want to Request?**
A way to disable the NSFW option

**Why do you need / want this feature?**
Because my server has some younger audiences and I do not want them to see the NSFW content

**Additional Remarks**
Add any other context or screenshots about the feature request to help us on making this happen.

**Comment by Deivu** [comment]
This is already been taken in consideration and now in On Hold Projects.

**Comment by XxBeastKingxX** [comment]
Thanks

**Comment by Deivu** [comment]
Pushed to Production, use **lewdset off** to disable it

**Comment by XxBeastKingxX** [comment]
Thank you very much 😀
