### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by tscar22** [Deivu/Kashima#2]
**Describe the bug**
the bot wont play music or wont resister that the emots that poped up where clicked
**Command / Feature that is Bugged**
The command that you used that isn't working right.
!play and !join
**What have you done before generating the bug?**
A clear and concise description of what you did.
used the bot before and it was working. the second imaage is that it resasured tha tthe song was called but it did not play the song.
**Screenshots**
![image](https://user-images.githubusercontent.com/42454821/44241568-bfcd4c80-a192-11e8-9362-39f5b6d8b8b8.png)
![image](https://user-images.githubusercontent.com/42454821/44241579-d07dc280-a192-11e8-97a6-26f338a39cc1.png)

**Additional remarks**
Other statement that may help us fix this bug.
my group enjoys the bot please just fix the music part please or if it is just our server pleases email me at alanfoleyjr@gmail

**Comment by Deivu** [comment]
Noted, A work around in this by calling playmoe and stop it, then use the music player again

**Comment by Deivu** [comment]
Update: I will Observe this now, I uploaded the patch to the production

**Comment by tscar22** [comment]
still doing the bug and the fix you told me stopped working. what do?

**Comment by tscar22** [comment]
the Japaneses moe is the only audio that work

**Comment by Deivu** [comment]
Could you clarify how this bug happens, so that I have a clear picture on where to look

**Comment by tscar22** [comment]
we did the !playmoe and let it run for about 2 min. then we did !stopmoe and the bot stopped then a member did !play  ______ it had been deleated so i cant tell you the next command all the way but that is the bases of what happend

**Comment by Deivu** [comment]
Ok, I did another minor patch, I'm not sure where this error comes from but I'll monitor for now. also make sure you react after the emojis have been displayed, not before the emojis is displayed

**Comment by tscar22** [comment]
ok thank you

**Comment by Deivu** [comment]
I cant now replicate this issue. Putting this in resolved now
