### ISSUE TITLE
!musicset bug

### ISSUE THREAD

**Issue by tscar22** [Deivu/Kashima#3]
**Describe the bug**

**Command / Feature that is Bugged**
The command that you used that isn't working right.

**What have you done before generating the bug?**
A clear and concise description of what you did.

**Screenshots**

**Additional remarks**
Other statement that may help us fix this bug.

**Comment by tscar22** [comment]
could not skip songs even though i am admen on the server 
  
![bug 1](https://user-images.githubusercontent.com/42454821/44315472-8266fa00-a3f2-11e8-8cc1-23618214cb27.PNG)
![bug 2](https://user-images.githubusercontent.com/42454821/44315474-8561ea80-a3f2-11e8-88af-a54794700eef.PNG)

**Comment by tscar22** [comment]
we where just lissening to music and wanted one of our members to stop skiping songs that they did not request

**Comment by Deivu** [comment]
Unrestricted Off = everyone can skip.
Restricted On = Manage Messages Perms / The member that added the song can skip the song.
Restricted DJ = Locks it to a role.
If you want to bind the music in a channel, use `musicbind`

Check the Wiki => Per Server Configuration Commands for more info.
