### ISSUE TITLE
just an idea that i would like you to consider

### ISSUE THREAD

**Issue by tscar22** [Deivu/Kashima#4]
**What is the feature that you want to Request?**
A clear and concise description of the feature you want.
if you could add a command slimier to the !neko but for anime dogs that is what my group would like
**Why do you need / want this feature?**
A clear and concise description of why should this be added to Kashima.
we really would like to have the bot be balanced on the way of cats and dogs and some of our members finally brought it to my attention and i wanted to raise it to yours. 
**Additional Remarks**
Add any other context or screenshots about the feature request to help us on making this happen.
my suggestion for the command would be !doggo or of some sort. thank you for considering this. i understand how hared it is to code a bot like this and i think you have done a great job. i am on discord if you need more info at A-Chan#1547

**Comment by takase1121** [comment]
@tscar22 what kind of anime dogs you want? Dog girls or real dogs?

**Comment by P4N3** [comment]
Girls

takase <notifications@github.com> schrieb am So., 26. Aug. 2018, 15:31:

**Comment by takase1121** [comment]
do you want nsfw or non nsfw or both?

**Comment by tscar22** [comment]
Both boy and girl anime dogs if possible. I am think of other servers that have this wonderful bot when I say both to the NSFW but please have it so that the command to turn on or off NSFW would be able to block the NSFW images is the block NSFW is turned on.

**Comment by P4N3** [comment]
Nsfw

takase <notifications@github.com> schrieb am So., 26. Aug. 2018, 15:33:

**Comment by takase1121** [comment]
i will try to work on it. I have my exam next week so I might not work now.

**Comment by tscar22** [comment]
School comes first so I would just like to know when you finish it.

**Comment by Deivu** [comment]
I just wanna add up to this. We do have a randomdog command since this feature has been delayed for sometime just incase you are wondering.

**Comment by tscar22** [comment]
is this command still being considered?
