### ISSUE TITLE
commands not working?

### ISSUE THREAD

**Issue by phantomicious** [Deivu/Kashima#5]
I just invited this kashima bot to my discord server but @kashima commands doesnt work? but the +voicequote commands work, I gave her permissions and everything

**Comment by phantomicious** [comment]
nvm  doing the +commands works but not @kashima and it says that its a prefix for a bot

**Comment by Deivu** [comment]
@phantomicious 

What the mention means is when you mentioned her, just a simple @Kashima would trigger her help command for you to use her.

Should have clarified it on that regard somewhere in documentation
