### ISSUE TITLE
МУЗЫКА

### ISSUE THREAD

**Issue by andrei083q** [Deivu/Kashima#6]
ЧЕРЕЗ КАКУЮ КОМАНДУ ЗАПУСТИТЬ МУЗЫКУ В ДИСКЕ

**Comment by Deivu** [comment]
Could you translate this in english?

**Comment by andrei083q** [comment]
> Не могли бы вы перевести это на английский?

USING WHICH COMMAND TO START THE MUSIC DISK

**Comment by Deivu** [comment]
+join then +play <search term, youtube link, youtubeplaylist>
