### ISSUE TITLE
Kashima won't play music starting from Nov 5th 2019

### ISSUE THREAD

**Issue by harlins** [Deivu/Kashima#7]
**Describe the bug**
Kashima won't play music starting from Nov 5th

**Command / Feature that is Bugged**
play

**What have you done before generating the bug?**
Nothing, it happened on another server too...

**Screenshots**
![image](https://user-images.githubusercontent.com/19322632/68313579-62028880-00e7-11ea-8f62-16c2378ad408.png)

**Additional remarks**
It was working on Nov 4th 2019

**Comment by tscar22** [comment]
Yes me and the head dev and his team have been working on it. YouTube has decided to ban our nodes periodically and we are trying to find a way to fix it so the search function doesn't work rn. But if you replace it with the URL it works fine

**Comment by harlins** [comment]
Ganbatte....

Kashima is my favorite waifu errr... music player, because after search, I can type number 1,2,3,4,5,6 directly to pick song.

Other's I have to type prefix and command then number.
Btw, how can I increase pick song timeout, it's too fast in my opinion.

**Comment by tscar22** [comment]
Currently there is no way to but you can join her support server  and suggest it.

https://discordapp.com/invite/FVqbtGu

**Comment by Deivu** [comment]
resolved as of December 2019
